In [144]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [27]:
data = pd.read_csv('processed_data.csv')

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10915 entries, 0 to 10914
Data columns (total 35 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Unnamed: 0          10915 non-null  int64  
 1   Business Name       10915 non-null  object 
 2   Average Rating      10915 non-null  float64
 3   Review Grade        10915 non-null  object 
 4   Title               10915 non-null  object 
 5   Review              10915 non-null  object 
 6   Rating              10915 non-null  int64  
 7   Time                10915 non-null  object 
 8   Review Count        10915 non-null  object 
 9   Country             10915 non-null  object 
 10  Status              5947 non-null   object 
 11  Month               10915 non-null  object 
 12  Month Numbers       10915 non-null  int64  
 13  Years               10915 non-null  object 
 14  Rating Distance     10915 non-null  float64
 15  body_neg            10915 non-null  float64
 16  body

In [31]:
data.drop(data.columns[[0,1,2,3,4]], axis = 1, inplace = True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10915 entries, 0 to 10914
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rating              10915 non-null  int64  
 1   Time                10915 non-null  object 
 2   Review Count        10915 non-null  object 
 3   Country             10915 non-null  object 
 4   Status              5947 non-null   object 
 5   Month               10915 non-null  object 
 6   Month Numbers       10915 non-null  int64  
 7   Years               10915 non-null  object 
 8   Rating Distance     10915 non-null  float64
 9   body_neg            10915 non-null  float64
 10  body_neu            10915 non-null  float64
 11  body_pos            10915 non-null  float64
 12  body_com            10915 non-null  float64
 13  title_neg           10915 non-null  float64
 14  title_neu           10915 non-null  float64
 15  title_pos           10915 non-null  float64
 16  titl

In [32]:
data.drop(data.columns[[1,4,5,6,7,8]], axis = 1, inplace = True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10915 entries, 0 to 10914
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rating              10915 non-null  int64  
 1   Review Count        10915 non-null  object 
 2   Country             10915 non-null  object 
 3   body_neg            10915 non-null  float64
 4   body_neu            10915 non-null  float64
 5   body_pos            10915 non-null  float64
 6   body_com            10915 non-null  float64
 7   title_neg           10915 non-null  float64
 8   title_neu           10915 non-null  float64
 9   title_pos           10915 non-null  float64
 10  title_com           10915 non-null  float64
 11  Title Length        10915 non-null  int64  
 12  Body Length         10915 non-null  int64  
 13  Total Length        10915 non-null  int64  
 14  Title Emoji         10915 non-null  int64  
 15  Body Emoji          10915 non-null  int64  
 16  Titl

In [117]:
ph_data = data[data['Country'] == 'PH']

In [118]:
ph_data.drop(['Country'], axis = 1, inplace = True)


In [119]:
ph_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6105 entries, 1 to 10914
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rating              6105 non-null   int64  
 1   Review Count        6105 non-null   object 
 2   body_neg            6105 non-null   float64
 3   body_neu            6105 non-null   float64
 4   body_pos            6105 non-null   float64
 5   body_com            6105 non-null   float64
 6   title_neg           6105 non-null   float64
 7   title_neu           6105 non-null   float64
 8   title_pos           6105 non-null   float64
 9   title_com           6105 non-null   float64
 10  Title Length        6105 non-null   int64  
 11  Body Length         6105 non-null   int64  
 12  Total Length        6105 non-null   int64  
 13  Title Emoji         6105 non-null   int64  
 14  Body Emoji          6105 non-null   int64  
 15  Title Ellipses      6105 non-null   int64  
 16  Body 

In [120]:
ph_data.drop(10, axis = 0, inplace = True)

In [121]:
ph_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6104 entries, 1 to 10914
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rating              6104 non-null   int64  
 1   Review Count        6104 non-null   object 
 2   body_neg            6104 non-null   float64
 3   body_neu            6104 non-null   float64
 4   body_pos            6104 non-null   float64
 5   body_com            6104 non-null   float64
 6   title_neg           6104 non-null   float64
 7   title_neu           6104 non-null   float64
 8   title_pos           6104 non-null   float64
 9   title_com           6104 non-null   float64
 10  Title Length        6104 non-null   int64  
 11  Body Length         6104 non-null   int64  
 12  Total Length        6104 non-null   int64  
 13  Title Emoji         6104 non-null   int64  
 14  Body Emoji          6104 non-null   int64  
 15  Title Ellipses      6104 non-null   int64  
 16  Body 

In [122]:
review_count = []

for row in ph_data['Review Count']:
    review_count.append(int(row))
    
ph_data['# Reviews'] = review_count
ph_data['Target Rating'] = ph_data['Rating']

<ipython-input-122-6d28182b2500>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ph_data['# Reviews'] = review_count
<ipython-input-122-6d28182b2500>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ph_data['Target Rating'] = ph_data['Rating']


In [123]:
ph_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6104 entries, 1 to 10914
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rating              6104 non-null   int64  
 1   Review Count        6104 non-null   object 
 2   body_neg            6104 non-null   float64
 3   body_neu            6104 non-null   float64
 4   body_pos            6104 non-null   float64
 5   body_com            6104 non-null   float64
 6   title_neg           6104 non-null   float64
 7   title_neu           6104 non-null   float64
 8   title_pos           6104 non-null   float64
 9   title_com           6104 non-null   float64
 10  Title Length        6104 non-null   int64  
 11  Body Length         6104 non-null   int64  
 12  Total Length        6104 non-null   int64  
 13  Title Emoji         6104 non-null   int64  
 14  Body Emoji          6104 non-null   int64  
 15  Title Ellipses      6104 non-null   int64  
 16  Body 

In [124]:
ph_data.drop(['Review Count'], axis = 1, inplace = True)
ph_data.drop(['Rating'], axis = 1, inplace = True)

In [125]:
ph_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6104 entries, 1 to 10914
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   body_neg            6104 non-null   float64
 1   body_neu            6104 non-null   float64
 2   body_pos            6104 non-null   float64
 3   body_com            6104 non-null   float64
 4   title_neg           6104 non-null   float64
 5   title_neu           6104 non-null   float64
 6   title_pos           6104 non-null   float64
 7   title_com           6104 non-null   float64
 8   Title Length        6104 non-null   int64  
 9   Body Length         6104 non-null   int64  
 10  Total Length        6104 non-null   int64  
 11  Title Emoji         6104 non-null   int64  
 12  Body Emoji          6104 non-null   int64  
 13  Title Ellipses      6104 non-null   int64  
 14  Body Ellipses       6104 non-null   int64  
 15  Title Hashtags      6104 non-null   int64  
 16  Body 

In [127]:
X = ph_data.iloc[:, 1:-1].values
y = ph_data.iloc[:, -1].values

In [134]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [139]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [147]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[501   0   0   0  59]
 [ 23   0   0   0   1]
 [ 18   0   0   0  23]
 [  9   0   0   1  61]
 [ 50   0   1   4 775]]


/Users/cheselle/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.8368283093053736

In [148]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[495   0   3   3  59]
 [ 20   0   1   0   3]
 [ 20   0   1   4  16]
 [ 10   0   2   6  53]
 [ 49   1   4  18 758]]


0.8256880733944955

In [149]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[505   0   0   0  55]
 [ 23   0   0   0   1]
 [ 18   0   0   0  23]
 [ 10   0   0   0  61]
 [ 54   0   0   0 776]]


0.8394495412844036

In [150]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[507   0   0   0  53]
 [ 22   0   0   0   2]
 [ 20   0   0   0  21]
 [  9   0   0   0  62]
 [ 53   0   0   0 777]]


0.8414154652686763

In [151]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 49 291 216   3   1]
 [  1  11  12   0   0]
 [  0  12  25   3   1]
 [  0   3  59   5   4]
 [  5  55 523 148  99]]


0.12385321100917432

In [152]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[472  18  10   4  56]
 [ 16   5   2   0   1]
 [ 12   4   3   4  18]
 [  9   1   4  11  46]
 [ 60   6  10  70 684]]


0.7699868938401049

In [153]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[510   0   0   1  49]
 [ 20   2   0   0   2]
 [ 17   0   1   3  20]
 [ 11   0   3   7  50]
 [ 60   1   2  24 743]]


0.827653997378768