In [170]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [186]:
data = pd.read_csv('processed_data.csv')

In [187]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10915 entries, 0 to 10914
Data columns (total 35 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Unnamed: 0          10915 non-null  int64  
 1   Business Name       10915 non-null  object 
 2   Average Rating      10915 non-null  float64
 3   Review Grade        10915 non-null  object 
 4   Title               10915 non-null  object 
 5   Review              10915 non-null  object 
 6   Rating              10915 non-null  int64  
 7   Time                10915 non-null  object 
 8   Review Count        10915 non-null  object 
 9   Country             10915 non-null  object 
 10  Status              5947 non-null   object 
 11  Month               10915 non-null  object 
 12  Month Numbers       10915 non-null  int64  
 13  Years               10915 non-null  object 
 14  Rating Distance     10915 non-null  float64
 15  body_neg            10915 non-null  float64
 16  body

In [188]:
data.drop(data.columns[[0,1,2,3,4,10]], axis = 1, inplace = True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10915 entries, 0 to 10914
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Review              10915 non-null  object 
 1   Rating              10915 non-null  int64  
 2   Time                10915 non-null  object 
 3   Review Count        10915 non-null  object 
 4   Country             10915 non-null  object 
 5   Month               10915 non-null  object 
 6   Month Numbers       10915 non-null  int64  
 7   Years               10915 non-null  object 
 8   Rating Distance     10915 non-null  float64
 9   body_neg            10915 non-null  float64
 10  body_neu            10915 non-null  float64
 11  body_pos            10915 non-null  float64
 12  body_com            10915 non-null  float64
 13  title_neg           10915 non-null  float64
 14  title_neu           10915 non-null  float64
 15  title_pos           10915 non-null  float64
 16  titl

In [190]:
data.drop(data.columns[[0,2,5,6,7,8]], axis = 1, inplace = True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10915 entries, 0 to 10914
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rating              10915 non-null  int64  
 1   Review Count        10915 non-null  object 
 2   Country             10915 non-null  object 
 3   body_neg            10915 non-null  float64
 4   body_neu            10915 non-null  float64
 5   body_pos            10915 non-null  float64
 6   body_com            10915 non-null  float64
 7   title_neg           10915 non-null  float64
 8   title_neu           10915 non-null  float64
 9   title_pos           10915 non-null  float64
 10  title_com           10915 non-null  float64
 11  Title Length        10915 non-null  int64  
 12  Body Length         10915 non-null  int64  
 13  Total Length        10915 non-null  int64  
 14  Title Emoji         10915 non-null  int64  
 15  Body Emoji          10915 non-null  int64  
 16  Titl

In [205]:
data.info()

ph_data = data[data['Country'] == 'PH']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10915 entries, 0 to 10914
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rating              10915 non-null  int64  
 1   Review Count        10915 non-null  object 
 2   Country             10915 non-null  object 
 3   body_neg            10915 non-null  float64
 4   body_neu            10915 non-null  float64
 5   body_pos            10915 non-null  float64
 6   body_com            10915 non-null  float64
 7   title_neg           10915 non-null  float64
 8   title_neu           10915 non-null  float64
 9   title_pos           10915 non-null  float64
 10  title_com           10915 non-null  float64
 11  Title Length        10915 non-null  int64  
 12  Body Length         10915 non-null  int64  
 13  Total Length        10915 non-null  int64  
 14  Title Emoji         10915 non-null  int64  
 15  Body Emoji          10915 non-null  int64  
 16  Titl

In [206]:
ph_data.drop(['Country'], axis = 1, inplace = True)
ph_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6105 entries, 1 to 10914
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rating              6105 non-null   int64  
 1   Review Count        6105 non-null   object 
 2   body_neg            6105 non-null   float64
 3   body_neu            6105 non-null   float64
 4   body_pos            6105 non-null   float64
 5   body_com            6105 non-null   float64
 6   title_neg           6105 non-null   float64
 7   title_neu           6105 non-null   float64
 8   title_pos           6105 non-null   float64
 9   title_com           6105 non-null   float64
 10  Title Length        6105 non-null   int64  
 11  Body Length         6105 non-null   int64  
 12  Total Length        6105 non-null   int64  
 13  Title Emoji         6105 non-null   int64  
 14  Body Emoji          6105 non-null   int64  
 15  Title Ellipses      6105 non-null   int64  
 16  Body 

/Users/cheselle/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [207]:
ph_data['Review Count'].value_counts()
ph_data.head(10)


Rating Review Count  body_neg  body_neu  body_pos  body_com  title_neg  \
1        4            1     0.000     1.000     0.000    0.0000      0.000   
2        5            1     0.000     0.854     0.146    0.4404      0.000   
3        5            1     0.000     1.000     0.000    0.0000      0.000   
4        5            1     0.183     0.817     0.000   -0.4005      0.000   
5        5            1     0.000     0.633     0.367    0.4404      0.000   
7        4            1     0.062     0.795     0.143    0.9690      0.000   
8        1            1     0.237     0.738     0.024   -0.9765      0.000   
9        1            1     0.237     0.738     0.024   -0.9765      0.000   
10       1       [Beer]     0.237     0.738     0.024   -0.9765      0.000   
14       1            1     0.141     0.859     0.000   -0.8885      0.761   

    title_neu  title_pos  title_com  ...  Total Length  Title Emoji  \
1       1.000        0.0     0.0000  ...            31            0   
2       1.000        0.0     0.0000  ...            36            0   
3       1.000        0.0     0.0000  ...            32            0   
4       1.000        0.0     0.0000  ...            30            0   
5       1.000        0.0     0.0000  ...            11            0   
7       1.000        0.0     0.0000  ...           251            0   
8       1.000        0.0     0.0000  ...           122            0   
9       1.000        0.0     0.0000  ...           122            0   
10      1.000        0.0     0.0000  ...           122            0   
14      0.239        0.0    -0.4898  ...           102            0   

    Body Emoji  Title Ellipses  Body Ellipses  Title Hashtags  Body Hashtags  \
1            0               0              0               0              0   
2            0               0              0               1              5   
3            0               0              0               1              5   
4            1               0              0               1              4   
5            1               0              0               1              1   
7            0               0              0               1              1   
8            0               0              1               1              3   
9            0               0              1               1              3   
10           0               0              1               1              3   
14           0               0              0               0              0   

    Title Exclamations  Body Exclamations  Status Rank  
1                    0                  0            1  
2                    0                  0            0  
3                    0                  0            0  
4                    0                  0            0  
5                    0                  0            0  
7                    0                  2            0  
8                    0                  3            1  
9                    0                  3            1  
10                   0                  3            1  
14                   3                  0            0  

[10 rows x 22 columns]

In [208]:
ph_data.drop(10, axis = 0, inplace = True)

/Users/cheselle/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [209]:
ph_data.head(10)

Rating Review Count  body_neg  body_neu  body_pos  body_com  title_neg  \
1        4            1     0.000     1.000     0.000    0.0000      0.000   
2        5            1     0.000     0.854     0.146    0.4404      0.000   
3        5            1     0.000     1.000     0.000    0.0000      0.000   
4        5            1     0.183     0.817     0.000   -0.4005      0.000   
5        5            1     0.000     0.633     0.367    0.4404      0.000   
7        4            1     0.062     0.795     0.143    0.9690      0.000   
8        1            1     0.237     0.738     0.024   -0.9765      0.000   
9        1            1     0.237     0.738     0.024   -0.9765      0.000   
14       1            1     0.141     0.859     0.000   -0.8885      0.761   
15       1            1     0.182     0.818     0.000   -0.7774      0.000   

    title_neu  title_pos  title_com  ...  Total Length  Title Emoji  \
1       1.000      0.000     0.0000  ...            31            0   
2       1.000      0.000     0.0000  ...            36            0   
3       1.000      0.000     0.0000  ...            32            0   
4       1.000      0.000     0.0000  ...            30            0   
5       1.000      0.000     0.0000  ...            11            0   
7       1.000      0.000     0.0000  ...           251            0   
8       1.000      0.000     0.0000  ...           122            0   
9       1.000      0.000     0.0000  ...           122            0   
14      0.239      0.000    -0.4898  ...           102            0   
15      0.507      0.493     0.4427  ...            49            0   

    Body Emoji  Title Ellipses  Body Ellipses  Title Hashtags  Body Hashtags  \
1            0               0              0               0              0   
2            0               0              0               1              5   
3            0               0              0               1              5   
4            1               0              0               1              4   
5            1               0              0               1              1   
7            0               0              0               1              1   
8            0               0              1               1              3   
9            0               0              1               1              3   
14           0               0              0               0              0   
15           0               0              0               0              0   

    Title Exclamations  Body Exclamations  Status Rank  
1                    0                  0            1  
2                    0                  0            0  
3                    0                  0            0  
4                    0                  0            0  
5                    0                  0            0  
7                    0                  2            0  
8                    0                  3            1  
9                    0                  3            1  
14                   3                  0            0  
15                   3                  0            1  

[10 rows x 22 columns]

In [210]:
review_count = []

for row in ph_data['Review Count']:
    review_count.append(int(row))
    
ph_data['# Reviews'] = review_count
ph_data['Target Rating'] = ph_data['Rating']

<ipython-input-210-6d28182b2500>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ph_data['# Reviews'] = review_count
<ipython-input-210-6d28182b2500>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ph_data['Target Rating'] = ph_data['Rating']


In [211]:
ph_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6104 entries, 1 to 10914
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rating              6104 non-null   int64  
 1   Review Count        6104 non-null   object 
 2   body_neg            6104 non-null   float64
 3   body_neu            6104 non-null   float64
 4   body_pos            6104 non-null   float64
 5   body_com            6104 non-null   float64
 6   title_neg           6104 non-null   float64
 7   title_neu           6104 non-null   float64
 8   title_pos           6104 non-null   float64
 9   title_com           6104 non-null   float64
 10  Title Length        6104 non-null   int64  
 11  Body Length         6104 non-null   int64  
 12  Total Length        6104 non-null   int64  
 13  Title Emoji         6104 non-null   int64  
 14  Body Emoji          6104 non-null   int64  
 15  Title Ellipses      6104 non-null   int64  
 16  Body 

In [212]:
ph_data.drop(['Review Count'], axis = 1, inplace = True)
ph_data.drop(['Rating'], axis = 1, inplace = True)

/Users/cheselle/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [ ]:
ph_data.iloc[:, 0:-1]

In [213]:
ph_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6104 entries, 1 to 10914
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   body_neg            6104 non-null   float64
 1   body_neu            6104 non-null   float64
 2   body_pos            6104 non-null   float64
 3   body_com            6104 non-null   float64
 4   title_neg           6104 non-null   float64
 5   title_neu           6104 non-null   float64
 6   title_pos           6104 non-null   float64
 7   title_com           6104 non-null   float64
 8   Title Length        6104 non-null   int64  
 9   Body Length         6104 non-null   int64  
 10  Total Length        6104 non-null   int64  
 11  Title Emoji         6104 non-null   int64  
 12  Body Emoji          6104 non-null   int64  
 13  Title Ellipses      6104 non-null   int64  
 14  Body Ellipses       6104 non-null   int64  
 15  Title Hashtags      6104 non-null   int64  
 16  Body 

In [214]:
X = ph_data.iloc[:, 0:-1].values
y = ph_data.iloc[:, -1].values

ph_data.head(5)

body_neg  body_neu  body_pos  body_com  title_neg  title_neu  title_pos  \
1     0.000     1.000     0.000    0.0000        0.0        1.0        0.0   
2     0.000     0.854     0.146    0.4404        0.0        1.0        0.0   
3     0.000     1.000     0.000    0.0000        0.0        1.0        0.0   
4     0.183     0.817     0.000   -0.4005        0.0        1.0        0.0   
5     0.000     0.633     0.367    0.4404        0.0        1.0        0.0   

   title_com  Title Length  Body Length  ...  Body Emoji  Title Ellipses  \
1        0.0             9           22  ...           0               0   
2        0.0             8           28  ...           0               0   
3        0.0             8           24  ...           0               0   
4        0.0             8           22  ...           1               0   
5        0.0             3            8  ...           1               0   

   Body Ellipses  Title Hashtags  Body Hashtags  Title Exclamations  \
1              0               0              0                   0   
2              0               1              5                   0   
3              0               1              5                   0   
4              0               1              4                   0   
5              0               1              1                   0   

   Body Exclamations  Status Rank  # Reviews  Target Rating  
1                  0            1          1              4  
2                  0            0          1              5  
3                  0            0          1              5  
4                  0            0          1              5  
5                  0            0          1              5  

[5 rows x 22 columns]

In [216]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [217]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [218]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[502   0   0   0  58]
 [ 23   0   0   0   1]
 [ 18   0   0   0  23]
 [  9   0   0   1  61]
 [ 51   0   2   2 775]]


0.8374836173001311

In [219]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[501   0   2   3  54]
 [ 21   0   1   0   2]
 [ 19   0   0   5  17]
 [ 11   0   3   5  52]
 [ 48   1   3  20 758]]


0.8283093053735255

In [220]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[504   0   0   0  56]
 [ 23   0   0   0   1]
 [ 18   0   0   0  23]
 [ 10   0   0   0  61]
 [ 56   0   0   0 774]]


0.8374836173001311

In [221]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[508   0   0   0  52]
 [ 22   0   0   0   2]
 [ 21   0   0   0  20]
 [  8   0   0   0  63]
 [ 53   0   0   0 777]]


0.8420707732634338

In [222]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 52 313 192   2   1]
 [  1  12  11   0   0]
 [  0  11  26   3   1]
 [  0   3  56   8   4]
 [  5  52 511 157 105]]


0.13302752293577982

In [223]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[478  17  10  11  44]
 [ 13   3   4   2   2]
 [ 13   2   4   3  19]
 [  8   2   4  15  42]
 [ 62   6  16  56 690]]


0.7798165137614679

In [224]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[508   0   3   3  46]
 [ 17   2   1   2   2]
 [ 17   1   2   3  18]
 [ 11   0   3   5  52]
 [ 51   0   5  22 752]]


0.8315858453473133